interface UIConstant {
  [key: string]: any;
}

export const UIConstants: UIConstant = {
  PROGRESS_CIRCLE_SIZE: 53,
  PROGRESS_CIRCLE_STROKE_WIDTH: 12,
  PROGRESS_CIRCLE_MAX_PROGRESS: 99,
  PROGRESS_CIRCLE_START_ANGLE: 0,
  PROGRESS_CIRCLE_FULL_ANGLE: 360,
  PROGRESS_FILLED_COLOR_START: '#2459AD',
  PROGRESS_FILLED_COLOR_END: '#0D2346',
  PROGRESS_UNFILLED_COLOR: 'rgba(225,225,225,0.9)',
  GRADIENT_X1: '16.15%',
  GRADIENT_Y1: '85.35%',
  GRADIENT_X2: '85.35%',
  GRADIENT_Y2: '16.15%',
  SAVE_ICON_COLOR: '#0D2346',
  PRIMARY_BUTTON_GRADIENT_COLORS: ['#FFFFFF', '#E8F0FC'],
  PADDING: 12,
  RHYTHM: 12,
};

export const EDGES_ALL_SIDES = ['top', 'bottom', 'left', 'right'] as const;
